Repository cse110-fa22-group25/warrantracker, pull requests merged in 2022-11, with the labels that each got.

#3 Continuous Integration Pipeline
  .eslintrc.json
  .github/workflows/continuous_integration.yml
  .gitignore
  README.md
  docs/fonts/OpenSans-Bold-webfont.eot
  docs/fonts/OpenSans-Bold-webfont.svg
  docs/fonts/OpenSans-Bold-webfont.woff
  docs/fonts/OpenSans-BoldItalic-webfont.eot
  docs/fonts/OpenSans-BoldItalic-webfont.svg
  docs/fonts/OpenSans-BoldItalic-webfont.woff
  docs/fonts/OpenSans-Italic-webfont.eot
  docs/fonts/OpenSans-Italic-webfont.svg
  docs/fonts/OpenSans-Italic-webfont.woff
  docs/fonts/OpenSans-Light-webfont.eot
  docs/fonts/OpenSans-Light-webfont.svg
  docs/fonts/OpenSans-Light-webfont.woff
  docs/fonts/OpenSans-LightItalic-webfont.eot
  docs/fonts/OpenSans-LightItalic-webfont.svg
  docs/fonts/OpenSans-LightItalic-webfont.woff
  docs/fonts/OpenSans-Regular-webfont.eot
  docs/fonts/OpenSans-Regular-webfont.svg
  docs/fonts/OpenSans-Regular-webfont.woff
  docs/global.html
  docs/home.js.html
  docs/index.html
  docs/scripts/linenumber.js
  docs/scripts/prettify/Apache-License-2.0.txt
  docs/scripts/prettify/lang-css.js
  docs/scripts/prettify/prettify.js
  docs/styles/jsdoc-default.css
  docs/styles/prettify-jsdoc.css
  docs/styles/prettify-tomorrow.css
  jsdoc.json
  package-lock.json
  package.json
  src/__tests__/empty.test.js
  src/index.html
  src/scripts/home.js
  src/scripts/test2.test.js
Labels: documentation, enhancement, good first issue, pipeline

#5 Need linter for HTML/CSS
  .github/workflows/ci.yml
  .htmlhintrc
  .stylelintrc.json
  README.md
  docs/global.html
  docs/home.js.html
  docs/index.html
  package-lock.json
  package.json
  src/index.css
Labels: documentation, enhancement, good first issue, pipeline

#8 Yoliang/starter code
  .eslintrc.json
  .stylelintignore
  docs/global.html
  docs/home.js.html
  docs/index.html
  package.json
  src/examples/modalExample.html
  src/examples/profileCardExample.html
  src/index.css
  src/index.html
  src/scripts/home.js
Labels: enhancement

#13 yoliang/code refactoring
  docs/Profile.html
  docs/global.html
  docs/home.js.html
  docs/index.html
  package-lock.json
  package.json
  src/__tests__/empty.test.js
  src/__tests__/src_home.test.js
  src/examples/profileCardExample.html
  src/index.html
  src/scripts/home.js
  src/scripts/test2.test.js
Labels: bug, documentation

#20 Delete button confirmation and functionality
  docs/Profile.html
  docs/global.html
  docs/home.js.html
  docs/index.html
  src/index.html
  src/scripts/home.js
Labels: enhancement

#22 Modify-product
  docs/Profile.html
  docs/global.html
  docs/home.js.html
  docs/index.html
  docs/setup.js.html
  src/__tests__/src_home.test.js
  src/index.html
  src/scripts/home.js
  src/scripts/setup.js
Labels: enhancement, help wanted

#34 Multi-filter
  src/index.html
  src/scripts/home.js
  src/scripts/setup.js
Labels: enhancement

#31 Tag feature
  docs/Profile.html
  docs/global.html
  docs/home.js.html
  docs/index.html
  docs/setup.js.html
  package-lock.json
  package.json
  src/__tests__/src_home.test.js
  src/index.html
  src/scripts/home.js
  src/scripts/setup.js
Labels: enhancement

#38 codeclimate config and small refactor of handle_tag_btn_click
  .codeclimate.yml
  README.md
  docs/Profile.html
  docs/global.html
  docs/home.js.html
  docs/index.html
  docs/setup.js.html
  src/scripts/home.js
Labels: enhancement, pipeline, Refactoring

#41 32-searching-for-profiles
  .codeclimate.yml
  docs/Profile.html
  docs/Profile.js.html
  docs/global.html
  docs/home.js.html
  docs/index.html
  docs/setup.js.html
  docs/storage.js.html
  src/__tests__/src_home.test.js
  src/index.html
  src/scripts/home.js
  src/scripts/setup.js
Labels: enhancement

#50 yoliang/deletion bug
  .gitignore
  docs/Profile.html
  docs/Profile.js.html
  docs/global.html
  docs/home.js.html
  docs/index.html
  docs/setup.js.html
  docs/storage.js.html
  src/index.css
  src/scripts/home.js
Labels: bug
