Repository cse110-fa22-group25/warrantracker, pull requests merged in 2022-12, with the labels that each got.

#47 yoliang/styling
  .stylelintignore
  docs/Profile.html
  docs/Profile.js.html
  docs/global.html
  docs/home.js.html
  docs/index.html
  docs/setup.js.html
  docs/storage.js.html
  package-lock.json
  src/__tests__/src_home.test.js
  src/img/team_logo.png
  src/img/team_logo_2.png
  src/index.css
  src/index.html
  src/scripts/home.js
  src/scripts/setup.js
Labels: Styling

#65 add parcel/e2e tests to pipeline
  .babelrc.json
  .github/workflows/ci.yml
  .gitignore
  babel.config.js
  docs/Profile.html
  docs/Profile.js.html
  docs/global.html
  docs/home.js.html
  docs/index.html
  docs/setup.js.html
  docs/storage.js.html
  jest-puppeteer.config.js
  package-lock.json
  package.json
  src/__tests__/openPage.test.js
  src/index.html
  src/scripts/home.js
Labels: enhancement, help wanted, pipeline

#68 Modify E2E test
  README.md
  docs/Profile.html
  docs/Profile.js.html
  docs/global.html
  docs/home.js.html
  docs/index.html
  docs/setup.js.html
  docs/storage.js.html
  jest-puppeteer.config.js
  package-lock.json
  package.json
  src/__tests__/e2e-version1.test.js
  src/__tests__/e2eSearchAndFilter.test.js
  src/__tests__/modify_unit_test.js
Labels: bug, help wanted

#69 fix info modal bugs
  docs/Profile.html
  docs/Profile.js.html
  docs/global.html
  docs/home.js.html
  docs/index.html
  docs/setup.js.html
  docs/storage.js.html
  src/index.html
  src/scripts/home.js
  src/scripts/setup.js
Labels: bug, Refactoring

#71 Deployment
  .codeclimate.yml
  .eslintrc.json
  .github/workflows/deploy.yml
  .htmlhintrc
  .stylelintrc.json
  README.md
  jsdoc.json
  package.json
  src/docs/Profile.html
  src/docs/Profile.js.html
  src/docs/fonts/OpenSans-Bold-webfont.eot
  src/docs/fonts/OpenSans-Bold-webfont.svg
  src/docs/fonts/OpenSans-Bold-webfont.woff
  src/docs/fonts/OpenSans-BoldItalic-webfont.eot
  src/docs/fonts/OpenSans-BoldItalic-webfont.svg
  src/docs/fonts/OpenSans-BoldItalic-webfont.woff
  src/docs/fonts/OpenSans-Italic-webfont.eot
  src/docs/fonts/OpenSans-Italic-webfont.svg
  src/docs/fonts/OpenSans-Italic-webfont.woff
  src/docs/fonts/OpenSans-Light-webfont.eot
  src/docs/fonts/OpenSans-Light-webfont.svg
  src/docs/fonts/OpenSans-Light-webfont.woff
  src/docs/fonts/OpenSans-LightItalic-webfont.eot
  src/docs/fonts/OpenSans-LightItalic-webfont.svg
  src/docs/fonts/OpenSans-LightItalic-webfont.woff
  src/docs/fonts/OpenSans-Regular-webfont.eot
  src/docs/fonts/OpenSans-Regular-webfont.svg
  src/docs/fonts/OpenSans-Regular-webfont.woff
  src/docs/global.html
  src/docs/home.js.html
  src/docs/index.html
  src/docs/scripts/linenumber.js
  src/docs/scripts/prettify/Apache-License-2.0.txt
  src/docs/scripts/prettify/lang-css.js
  src/docs/scripts/prettify/prettify.js
  src/docs/setup.js.html
  src/docs/storage.js.html
  src/docs/styles/jsdoc-default.css
  src/docs/styles/prettify-jsdoc.css
  src/docs/styles/prettify-tomorrow.css
  src/index.html
Labels: documentation, enhancement, pipeline

#72 update readme with deployed links and fix typo in docs
  README.md
  src/docs/Profile.html
  src/docs/Profile.js.html
  src/docs/global.html
  src/docs/home.js.html
  src/docs/index.html
  src/docs/setup.js.html
  src/docs/storage.js.html
  src/scripts/home.js
Labels: documentation, enhancement

#77 update tag btn overflow property
  src/docs/Profile.html
  src/docs/Profile.js.html
  src/docs/global.html
  src/docs/home.js.html
  src/docs/index.html
  src/docs/setup.js.html
  src/docs/storage.js.html
  src/index.css
Labels: bug
